# Generated by Django 4.0.4 on 2022-05-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_interface', '0002_alter_video_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='comments',
        ),
        migrations.AddField(
            model_name='video',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
