# Generated by Django 4.0.4 on 2022-12-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_interface', '0040_alter_thumbnail_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='image_file',
            field=models.ImageField(upload_to='images/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
