# Generated by Django 4.0.4 on 2022-05-09 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos_interface', '0011_alter_video_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Random',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos_interface.comment')),
            ],
        ),
    ]
