# Generated by Django 4.0.4 on 2022-05-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_interface', '0015_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='clicks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
