# Generated by Django 4.0.4 on 2022-05-11 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos_interface', '0018_clicks_user_clicks_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clicks',
            options={'verbose_name': 'Click', 'verbose_name_plural': 'Clicks'},
        ),
    ]
