# Generated by Django 4.0.4 on 2022-05-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_interface', '0022_video_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='clicks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
