# Generated by Django 4.0.4 on 2022-12-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_interface', '0035_video_views_delete_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='image_path',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
