# Generated by Django 4.0.4 on 2022-05-14 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simplemodel',
            old_name='occuptation',
            new_name='occupation',
        ),
    ]
