# Generated by Django 4.0.4 on 2022-05-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
