# Generated by Django 4.0.4 on 2022-05-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_interface', '0004_video_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
