# Generated by Django 4.0.4 on 2022-05-09 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos_interface', '0007_remove_video_comments_alter_user_email_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='comment_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='video_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos_interface.video'),
        ),
    ]
