# Generated by Django 4.0.4 on 2022-05-09 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos_interface', '0009_alter_comment_user_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='video_id',
            new_name='video',
        ),
    ]
