# Generated by Django 4.0.4 on 2022-05-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos_interface', '0026_alter_thumbnail_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='thumbnail',
        ),
    ]
