# Generated by Django 4.0.4 on 2022-06-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_interface', '0030_alter_thumbnail_image_alter_video_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(blank=True, upload_to='videos/', verbose_name=''),
        ),
    ]
