# Generated by Django 4.0.4 on 2022-12-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_interface', '0034_remove_thumbnail_image_thumbnail_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Clicks',
        ),
    ]
