# Generated by Django 4.0.4 on 2022-12-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_interface', '0036_alter_thumbnail_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='image_path',
            field=models.ImageField(default='no thumbnail', upload_to='images/', verbose_name=''),
            preserve_default=False,
        ),
    ]
