# Generated by Django 4.0.4 on 2022-12-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos_interface', '0037_alter_thumbnail_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnail',
            old_name='image_path',
            new_name='image_file',
        ),
    ]
