# Generated by Django 4.1 on 2023-06-02 23:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos_interface', '0041_alter_thumbnail_image_file_alter_video_videofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
