# Generated by Django 4.1 on 2024-01-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos_interface', '0042_video_created_video_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='video',
            name='views',
        ),
    ]
